### ISSUE TITLE
[Feature request] Allow nesting routers

### ISSUE THREAD

**Issue by snelsi** [HuolalaTech/react-query-kit#43]
## Describe the issue you have

[router](https://github.com/HuolalaTech/react-query-kit?tab=readme-ov-file#router) was introduced in `v3.0.0`.

In a way, it acts very similar to [TRPC Routers](https://trpc.io/docs/server/routers).
However unlike `tRPC`, `react-query-kit` atm doesn't allow merging/nesting multiple routers.

And I think in its current state it's not super convenient to use.

The idea behind a `router` is to logically group and map 1 backend API endpoint to 1 custom query hook.
And the backend's API is never _'flat'_. Endpoints can have any number of sub-segments in the URL.

## Example

Imagine, if my backend has these endpoints available:
- GET `/api/users`
- POST `/api/users`
- POST  `/api/users/command/report`
- POST  `/api/users/command/promote`

Current [README example](https://github.com/HuolalaTech/react-query-kit?tab=readme-ov-file#merging-routers) proposes either to create 1 router for everything or use a plain js object to merge 2 routers into one.
However, the `/users/command` router is clearly a sub-group of `/users`. So I would like to nest the `command` router inside of the `users` router. And `react-query-kit` doesn't provide a clear way to achieve this.

For me, the ideal router config for those endpoints would look something like this:

```tsx
import { router } from "react-query-kit";

const command = router("command", {
  report: router.mutation(...),
  promote: router.mutation(...)
})

const api = router("users", {
  command, // <-- nest router inside of another router
  
  get: router.query(...),
  create: router.mutation(...)
})

const api = router("api", {
  users, // <-- nest router inside of another router
  
  // Add other routers here in the future
  // ...
})
```

Then, I can use the created `api` router like this:

```tsx

api.users.get.useQuery();
api.users.create.useMutation();
api.users.command.report.useMutation();
api.users.command.promote.useMutation();
```

## Proposed solution

Extend `react-query-kit` `router`'s functionality to include nesting/merging child routers.
Update Typescript types to allow nesting routers.

Use [this example](https://trpc.io/docs/server/merging-routers) as a useful reference

**Comment by liaoliao666** [comment]
Support nest router in v3.1.0
const post = router(`post`, {
  byId: router.query({
    fetcher: (variables: { id: number }) =>
      fetch(`/posts/${variables.id}`).then(res => res.json()),
    use: [myMiddleware],
  }),

  list: router.infiniteQuery({
    fetcher: (_variables, { pageParam }) =>
      fetch(`/posts/?cursor=${pageParam}`).then(res => res.json()),
    getNextPageParam: lastPage => lastPage.nextCursor,
    initialPageParam: 0,
  }),

  add: router.mutation({
    mutationFn: async (variables: { title: string; content: string }) =>
      fetch('/posts', {
        method: 'POST',
        body: JSON.stringify(variables),
      }).then(res => res.json()),
  }),

  // nest router
  command: {
    report: router.mutation({ mutationFn }),

    promote: router.mutation({ mutationFn }),
  },
})

**Comment by snelsi** [comment]
Just updated my project to `v3.1.0`
Seems to work fine
Thanks @liaoliao666 🔥
