### ISSUE TITLE
Ability to pass `string | string[]` into Router as the key?

### ISSUE THREAD

**Issue by ElliotChong** [HuolalaTech/react-query-kit#49]
Greetings! I've been evaluating your library for use in a future project and think it's an awesome tool for adding structure to TanStack Query. Thank you for open sourcing it and sharing it with the world!

I'm particularly interested in using the `router` pattern you've created; however, one limitation I see is that I wouldn't be able to pass in an Array of Strings into the `router` method to be able to do something like `['user', 'some-id-123', 'post']` to scope it and make cache invalidation easier to work with for a given user. Would you support adding a `keyPrefix` option so that the exported object would still be `{ post: { ... } }` but the inner key used by TanStack Query is prefixed?

https://github.com/HuolalaTech/react-query-kit/blob/bc94ef38687db743119a97fb100ce2f140a999be/src/router.ts#L56-L61

# Proposed Modificaiton
```
export const router = <TConfig extends RouterConfig>(
  key: string,
  config: TConfig,
  keyPrefix?: string[]
): CreateRouter<TConfig> => {
  if (!keyPrefix) {
    return buildRouter([key], config)
  }

  const router = buildRouter([...keyPrefix, key], config)
  return keyPrefix.reduce((acc, key) => acc[key], router);
}
```

**Comment by ElliotChong-MS** [comment]
Alternatively... Is there be a way to modify the `cacheKey` via middleware? 🤔

**Comment by ElliotChong** [comment]
Alternatively... Is there be a way to modify the cacheKey via middleware? 🤔Alternatively... Is there be a way to modify the cacheKey via middleware? 🤔

**Comment by liaoliao666** [comment]
> Alternatively... Is there be a way to modify the cacheKey via middleware? 🤔

Same as this issue https://github.com/HuolalaTech/react-query-kit/issues/44. You can only modify cache key by `variables` option.

**Comment by liaoliao666** [comment]
Finally I decided to implement this feature through the following code. Do you have any further questions?

```ts
export const router = <TConfig extends RouterConfig>(
  key: unknown | unknown[],
  config: TConfig,
): CreateRouter<TConfig> => {
  return buildRouter(Array.isArray(key) ? key : [key], config)
}
```

**Comment by ElliotChong** [comment]
Thank you so much for the quick turn around! 🙇‍♂️

Re: changing the type to `unknown`, are there any concerns with generating the `Object` router returns if the keys are anything other than string?

**Comment by liaoliao666** [comment]
> Thank you so much for the quick turn around! 🙇‍♂️
> 
> Re: changing the key type to `unknown`, are there any concerns with generating the `Object` router returns if the keys are anything other than string?

Also works fine if passing object key. 
And Because `unknown` type includes `unknown[]`. So the ultimate code is:
```ts
export const router = <TConfig extends RouterConfig>(
  key: string | unknown[],
  config: TConfig,
): CreateRouter<TConfig> => {
  return buildRouter(Array.isArray(key) ? key : [key], config)
}
```

**Comment by ElliotChong** [comment]
What does the shape of the Object returned by `buildRouter` look like in this instance?
```
const foo = router(['foo', { bar: 'baz }, 'bang'], { ... });
```

**Comment by liaoliao666** [comment]
Already support at v3.2.0

**Comment by ElliotChong-MS** [comment]
Thanks so much @liaoliao666
