### ISSUE TITLE
Error: queryFn is not supported, please use fetcher instead

### ISSUE THREAD

**Issue by AngyDev** [HuolalaTech/react-query-kit#52]
Hi, I'm migrating to version 3, I'm following the instructions but I keep getting this error 

[Bug] queryFn is not supported, please use fetcher instead.

on this code:

```
const { data: projectOverviews, isLoading } = createQuery(
  getAllProjects.getOptions() as unknown as CreateQueryOptions<ProjectMDL[], void, Error>,
)();
```

within getAllProjects I'm using the new fetcher function. So, I don't understand why I still get this error, any idea what is causing this? 
Thank you

**Comment by liaoliao666** [comment]
u should use `useQuery` instead of  `useQuery`, as below
```ts
const { data: projectOverviews, isLoading } = useQuery(
  getAllProjects.getOptions()
)();
```

or
```ts
const { data: projectOverviews, isLoading } = getAllProjects()
```

**Comment by AngyDev** [comment]
Perfect, thank you
