### ISSUE TITLE
Invalidate a query when using router.query

### ISSUE THREAD

**Issue by Mallikarjun31** [HuolalaTech/react-query-kit#54]
How do we invalidate a query when using router.query

router.query is not accepting queryKey as parameter, it is accepting queryHash, but when using queryHash as value to 

`queryClient.invalidateQueries`

it is not making the API call again. 

Please help

**Comment by liaoliao666** [comment]
is this?
```ts
queryClient.invalidateQueries({
      queryKey: post.byId.getKey(),
 })
```

**Comment by Mallikarjun31** [comment]
yes @liaoliao666 . This did not work

**Comment by liaoliao666** [comment]
can you show me a reproduce example?

**Comment by Mallikarjun31** [comment]
This is my router query

```
getRoadmapCards: router.query({
    fetcher: () => axios.get(`${pubUrl}/pub/api/task-board/cards`, { withCredentials: true }),
  }),
```

And i am trying to invalidate it using

```
queryClient.invalidateQueries({
      queryKey: roadmapCardsApis.getRoadmapCards.getKey(),
    })
```

**Comment by liaoliao666** [comment]
Seems it is no problem, maybe you should inspect your code. or provide a codesanbox example to me.
