### ISSUE TITLE
`select` is intentionally removed from `createQuery`

### ISSUE THREAD

**Issue by denisborovikov** [HuolalaTech/react-query-kit#57]
The `select` option is intentionally omitted in `createQuery` [here](https://github.com/HuolalaTech/react-query-kit/blob/028168d8e0bc00705b9c25d1894b4d4a74ba7835/src/types.ts#L161) but it's not reflected in the docs. What was the reason for this? Could you explain?

**Comment by liaoliao666** [comment]
It will break the work of typescript and intuition.

**Comment by denisborovikov** [comment]
I think it makes sense to mention this in the docs and offer an alternative way to resolve the problem the `select` intends to solve.

**Comment by liaoliao666** [comment]
Similar with this issue https://github.com/HuolalaTech/react-query-kit/issues/8
