### ISSUE TITLE
Running mutation outside of react component

### ISSUE THREAD

**Issue by denisborovikov** [HuolalaTech/react-query-kit#58]
Hi,

First of all, thank you for the great library.

In the docs about `createMutation` you have an example of running the mutation outside the react component.

```js
useAddTodo.mutationFn({ title: 'Do Laundry', content: 'content...' })
```

It's crucial to note that this request simply runs the mutation function, bypassing the options and middlewares of the `createMutation`. I.e. if I have a middleware to invalidate a query after the mutation, it won't be executed.

Is this possible to add a method that works the same way as `mutateAsync` (returns a promise) that can be run outside of the react component and respects all of the `createMutation` options and middlewares?

E.g.

```
useAddTodo.mutateAsync()  // runs mutationFn, executes middlewares
```

Thank you!

**Comment by denisborovikov** [comment]
It would be possible to use `queryClient.getMutationCache()` to register and execute a mutation. The syntax is 

```js
queryClient 
     .getMutationCache() 
     .build(queryClient, options) 
     .execute() 
```
But the options must be after applying all the middleware logic. `getOptions()` returns the original options from `createQuery`.

**Comment by liaoliao666** [comment]
The middleware only works in the react component like other hooks

**Comment by denisborovikov** [comment]
Oh true
