### ISSUE TITLE
TS reference error when trying to invalidate router query

### ISSUE THREAD

**Issue by funabab** [HuolalaTech/react-query-kit#59]
Trying to invalidate a query using router variable causes TS reference error, thereby preventing using router .getKey() to invalidate queries in mutation callbacks.

![Screenshot from 2024-06-09 13-53-25](https://github.com/HuolalaTech/react-query-kit/assets/60202749/cb0b42f6-ba95-4af9-ba80-1810b68b100b)

### A sample project demonstrating this 

https://codesandbox.io/p/sandbox/react-query-kit-invalidate-ref-error-yr4cqq?file=%2Fsrc%2Froutes.ts%3A14%2C14-14%2C19

**Comment by funabab** [comment]
One solution that was provided is to manually type the OnSuccess method.

```javascript
OnSuccess(): Promise<QueryKey> {
...
}
```

While this works, it isn't documented.

**Comment by liaoliao666** [comment]
It is no problem, it is typescript behaviour and work well
