### ISSUE TITLE
Variables Optional

### ISSUE THREAD

**Issue by m4ttheweric** [HuolalaTech/react-query-kit#60]
Hi, this is somewhat of a question on the design.

When a query requires variables, the `variables` property on the resulting `QueryHook` is optional no matter what.

This seems less-than ideal as it allows developers to implement the hook incorrectly and only discover the issue when the query fails due to missing arguments.

I'm curious what the thought process was behind this design choice and if it's something that can be controlled.

Thanks!

Matt

**Comment by liaoliao666** [comment]
Because the variables option may comes from other way. Like
```ts
createQuery({ variables: {...} })
```
or
```ts
createQuery({ use: [useNext => (options) => useNext({options, variables: {...} })]})
```
