### ISSUE TITLE
getOptions() & getFetchOptions() is typed incorrectly

### ISSUE THREAD

**Issue by ElliotChong-MS** [HuolalaTech/react-query-kit#61]
Greetings!

When upgrading to the latest `3.3.0` version it appears that the types for `getOptions` and `getFetchOptions` were broken and now requires a variables argument (which is typed as `any`) and always returns `any`.
<img width="923" alt="image" src="https://github.com/HuolalaTech/react-query-kit/assets/77078627/7a9a2a15-1ce3-40ac-9ee0-be80dcb19bce">

**Comment by liaoliao666** [comment]
which ReactQuery version you depend on?

**Comment by ElliotChong-MS** [comment]
Currently @ `5.45.0` which is the latest, will try and work up a codesandbox example soon. Thanks!

**Comment by ElliotChong-MS** [comment]
I downgraded to `react-query-kit` 3.2.2 to try and narrow the changeset down and that version does not repro the TS issue.

**Comment by ElliotChong-MS** [comment]
I've narrowed it down: I'm pulling `@tanstack/query-core` into my project but `react-query-kit` is looking for `@tanstack/react-query`. Interesting that the move from `3.2.2` to `3.3.0` broke that, but based on `peerDependencies` I should have been including `@tanstack/react-query` anyways.
