### ISSUE TITLE
react-query 5 - QueryClient's use param not found

### ISSUE THREAD

**Issue by SGeri** [HuolalaTech/react-query-kit#65]
When I try to create global middlewares using the `use` parameter of the query client's default options, I get a simple error showing that this field does not exist. There is no such thing like that use field in official react-query docs, so I don't really understand how this is supposed to work, even though the react-query-kit docs show the exact code for this machanism.
Can someone explain this?

```
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      use: [queryMiddleware],
    },
    mutations: {
      use: [mutationMiddleware],
    },
  },
})
```

**Comment by liaoliao666** [comment]
You need to extend the queryclient interface yourself

**Comment by SGeri** [comment]
alright, thanks. I thought there was a built-in method for extending the base type.
